- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Get EPGs from ACI
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        state: query
